version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fireequip_postgres
   # restart: always
    environment:
      POSTGRES_DB: fireequipdb
      POSTGRES_USER: fireequip
      POSTGRES_PASSWORD: fireequip
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fireequip_backend
   # restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fireequipdb
      SPRING_DATASOURCE_USERNAME: fireequip
      SPRING_DATASOURCE_PASSWORD: fireequip

volumes:
  postgres_data: