spring.application.name=FireequipBackendApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/fireequipdb
spring.datasource.username=fireequip
spring.datasource.password=fireequip

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080